# vi: sw=2 ts=2 sts=2 expandtab

language: python
dist: xenial
sudo: false
services:
  - xvfb

addons:
  apt:
    packages:
      - herbstluftwm

env:
   global:
      - OFFICIAL_REPO="pcdshub/pyqt-designer-plugin-entry-points"
      - secure: ""

matrix:
  fast_finish: true
  include:
    - name: Style checking
      python: 3.6
      env: LINT_PYTHON=pyqt-designer-plugin-entry-points
    - name: Python 3.6 Unit Tests
      python: 3.6
      env:
        - UNIT_TEST=1
        - UPLOAD=1
    - name: Python 3.7 Unit Tests
      python: 3.7
      env: UNIT_TEST=1
    - name: Python 3.8 Unit Tests
      python: 3.8
      env: UNIT_TEST=1
    - name: Build Docs
      python: 3.6
      env: BUILD_DOCS=1
  allow_failures:
    - name: Python 3.8 Unit Tests
      python: 3.8
      env: UNIT_TEST=1

install:
  # Import the helper scripts
  - git clone --depth 1 git://github.com/pcdshub/pcds-ci-helpers.git
  # Start the helper-script initialization + run based on environment variables
  - source pcds-ci-helpers/travis/init.sh

  # Install and configure miniconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source $HOME/miniconda/etc/profile.d/conda.sh
  - conda activate base
  - conda config --set always_yes yes --set changeps1 no

  # Ensure all packages are up-to-date
  - conda update -q conda
  - conda install conda-build
  - conda config --append channels pcds-tag
  - conda config --append channels conda-forge
  - conda info -a

  # Test conda build and create test environment
  - |
    if [[ $UNIT_TEST || $BUILD_DOCS ]]; then
      echo "Building full environment"
      set -e
      conda build -q conda-recipe --python $TRAVIS_PYTHON_VERSION --output-folder bld-dir
      conda config --add channels "file://`pwd`/bld-dir"
      conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pyqt-designer-plugin-entry-points --file dev-requirements.txt
      set +e
    fi

  - conda activate test-environment
  # Install any additional development requirements
  - pip install -Ur dev-requirements.txt
  # Install the package itself
  - pip install -e .


before_script:
  # Run windows manager
  - "herbstluftwm &"
  - sleep 1


script:
  - |
    if [[ $UNIT_TEST ]]; then
      echo "Running tests"
      coverage run -m pytest -vv
    fi
  - |
    if [[ $UNIT_TEST ]]; then
      coverage report -m
    fi

  - |
    if [[ -n "$DOCTR_DEPLOY_ENCRYPTION_KEY_PCDSHUB_PYQT-DESIGNER-PLUGIN-ENTRY-POINTS" && $BUILD_DOCS ]]; then
      # Create HTML documentation
      set -e
      pushd docs
      make html
      popd
      #Publish docs.
      doctr deploy . --built-docs docs/build/html --deploy-branch-name gh-pages --command "touch .nojekyll; git add .nojekyll"
      set +e
    fi
